spring.application.name=oona-be
server.port=8083

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/OonaDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=sql17!

# Seguridad JWT (expiration: 15 minutos en ms)
api.security.token.secret=$cPXnSJEKQ9nKBN8geskfb^$gtIY21.Op93D9lK$Lykj1&X^3TKL$mcsu%Xj5@kE8iVv@iwvdg&ZkI/lkxq0I5vHiEXlD!Pg/00rmiu7JYOJCCSV.MjN!U7EL3m$#52C
api.security.token.expiration=900000