# ===================================================================
# CONFIGURACIÓN PARA ENTORNO DE PRODUCCIÓN / CONTENEDORES (prod)
# ===================================================================

# Base de Datos de Producción / Contenedor
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Producción
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Logger producción
logging.level.org.springframework.security=INFO
logging.level.com.hean.consigueventas.oonabe=INFO
