CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) UNIQUE,
    password_hash VARCHAR(255),
    email VARCHAR(150) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ultimo_acceso_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_usuarios_estado CHECK (estado IN ('ACTIVO', 'SUSPENDIDO', 'DESACTIVADO'))
);

CREATE TABLE usuario_roles (
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE ciudades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    provincia VARCHAR(100),
    pais_codigo VARCHAR(2) NOT NULL DEFAULT 'ES',
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ubicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    ciudad_id BIGINT REFERENCES ciudades(id) ON DELETE SET NULL,
    latitud NUMERIC(9, 6),
    longitud NUMERIC(9, 6),
    indicaciones TEXT,
    activo BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_ubicaciones_latitud CHECK (latitud IS NULL OR latitud BETWEEN -90 AND 90),
    CONSTRAINT chk_ubicaciones_longitud CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

CREATE TABLE categorias_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT,
    imagen_url TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE especialidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE perfil_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(25),
    ciudad_preferida_id BIGINT REFERENCES ciudades(id) ON DELETE SET NULL,
    fecha_nacimiento DATE,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE perfil_profesionales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
    slug VARCHAR(160) NOT NULL UNIQUE,
    nombre_publico VARCHAR(150) NOT NULL,
    biografia TEXT NOT NULL,
    foto_url TEXT NOT NULL,
    telefono_whatsapp VARCHAR(25) NOT NULL,
    email_publico VARCHAR(150),
    sitio_web TEXT,
    estado_aprobacion VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    estado_publicacion VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    aprobado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    aprobado_at TIMESTAMPTZ,
    motivo_rechazo VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_perfil_prof_estado_aprobacion CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    CONSTRAINT chk_perfil_prof_estado_publicacion CHECK (estado_publicacion IN ('BORRADOR', 'PUBLICADO', 'OCULTO'))
);

CREATE TABLE redes_profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE CASCADE,
    tipo VARCHAR(30) NOT NULL,
    url TEXT NOT NULL,
    orden SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_redes_profesional_tipo CHECK (tipo IN ('INSTAGRAM', 'LINKEDIN', 'YOUTUBE', 'WEB'))
);

CREATE TABLE imagenes_profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    texto_alternativo VARCHAR(180),
    es_portada BOOLEAN NOT NULL DEFAULT FALSE,
    formato VARCHAR(10),
    peso_bytes INTEGER,
    orden SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_imagenes_profesional_formato CHECK (formato IS NULL OR formato IN ('JPG', 'PNG', 'WEBP')),
    CONSTRAINT chk_imagenes_profesional_peso CHECK (peso_bytes IS NULL OR peso_bytes >= 0)
);

CREATE TABLE profesional_especialidades (
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE CASCADE,
    especialidad_id BIGINT NOT NULL REFERENCES especialidades(id) ON DELETE RESTRICT,
    PRIMARY KEY (profesional_id, especialidad_id)
);

CREATE TABLE eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    titulo VARCHAR(180) NOT NULL,
    resumen VARCHAR(300),
    descripcion TEXT NOT NULL,
    modalidad VARCHAR(15) NOT NULL,
    tipo_reserva VARCHAR(20) NOT NULL,
    url_reserva_externa TEXT,
    precio_desde NUMERIC(10, 2),
    moneda VARCHAR(3) NOT NULL DEFAULT 'EUR',
    edad_minima SMALLINT,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    destacado BOOLEAN NOT NULL DEFAULT FALSE,
    creado_por BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    aprobado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    aprobado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_eventos_modalidad CHECK (modalidad IN ('PRESENCIAL', 'ONLINE', 'HIBRIDA')),
    CONSTRAINT chk_eventos_tipo_reserva CHECK (tipo_reserva IN ('INTERNA', 'EXTERNA', 'CONTACTO')),
    CONSTRAINT chk_eventos_estado CHECK (estado IN ('BORRADOR', 'REVISION', 'PUBLICADO', 'CANCELADO', 'ARCHIVADO')),
    CONSTRAINT chk_eventos_precio_desde CHECK (precio_desde IS NULL OR precio_desde >= 0),
    CONSTRAINT chk_eventos_edad_minima CHECK (edad_minima IS NULL OR edad_minima >= 0)
);

CREATE TABLE evento_categorias (
    evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    categoria_id BIGINT NOT NULL REFERENCES categorias_evento(id) ON DELETE RESTRICT,
    PRIMARY KEY (evento_id, categoria_id)
);

CREATE TABLE evento_profesionales (
    evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE RESTRICT,
    rol_en_evento VARCHAR(30) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (evento_id, profesional_id),
    CONSTRAINT chk_evento_profesionales_rol CHECK (rol_en_evento IN ('ORGANIZADOR', 'FACILITADOR', 'COLABORADOR'))
);

CREATE TABLE imagenes_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    texto_alternativo VARCHAR(180),
    es_portada BOOLEAN NOT NULL DEFAULT FALSE,
    formato VARCHAR(10),
    peso_bytes INTEGER,
    orden SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_imagenes_evento_formato CHECK (formato IS NULL OR formato IN ('JPG', 'PNG', 'WEBP')),
    CONSTRAINT chk_imagenes_evento_peso CHECK (peso_bytes IS NULL OR peso_bytes >= 0)
);

CREATE TABLE ocurrencias_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    inicio_at TIMESTAMPTZ NOT NULL,
    fin_at TIMESTAMPTZ NOT NULL,
    ubicacion_id BIGINT REFERENCES ubicaciones(id) ON DELETE SET NULL,
    capacidad INTEGER NOT NULL,
    cupos_reservados INTEGER NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADA',
    url_virtual TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_ocurrencias_evento_estado CHECK (estado IN ('PROGRAMADA', 'AGOTADA', 'CANCELADA', 'FINALIZADA')),
    CONSTRAINT chk_ocurrencias_evento_fechas CHECK (fin_at > inicio_at),
    CONSTRAINT chk_ocurrencias_evento_cupos CHECK (capacidad >= 0 AND cupos_reservados >= 0 AND cupos_reservados <= capacidad)
);

CREATE TABLE servicios_1a1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE RESTRICT,
    slug VARCHAR(180) NOT NULL UNIQUE,
    titulo VARCHAR(180) NOT NULL,
    descripcion TEXT NOT NULL,
    duracion_minutos INTEGER NOT NULL,
    modalidad VARCHAR(15) NOT NULL,
    ubicacion_id BIGINT REFERENCES ubicaciones(id) ON DELETE SET NULL,
    precio NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL DEFAULT 'EUR',
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    aprobado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    aprobado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_servicios_modalidad CHECK (modalidad IN ('PRESENCIAL', 'ONLINE', 'AMBAS')),
    CONSTRAINT chk_servicios_estado CHECK (estado IN ('BORRADOR', 'PUBLICADO', 'OCULTO')),
    CONSTRAINT chk_servicios_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT chk_servicios_precio CHECK (precio >= 0)
);

CREATE TABLE disponibilidad_profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE CASCADE,
    dia_semana SMALLINT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    ubicacion_id BIGINT REFERENCES ubicaciones(id) ON DELETE SET NULL,
    vigente_desde DATE NOT NULL,
    vigente_hasta DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_disponibilidad_dia CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT chk_disponibilidad_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT chk_disponibilidad_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
);

CREATE TABLE bloqueos_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE CASCADE,
    inicio_at TIMESTAMPTZ NOT NULL,
    fin_at TIMESTAMPTZ NOT NULL,
    motivo VARCHAR(255),
    CONSTRAINT chk_bloqueos_agenda_fechas CHECK (fin_at > inicio_at)
);

CREATE TABLE ordenes_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    cliente_id BIGINT NOT NULL REFERENCES perfil_clientes(id) ON DELETE RESTRICT,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
    descuento_total NUMERIC(10, 2) NOT NULL DEFAULT 0,
    importe_total NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL DEFAULT 'EUR',
    estado VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
    expira_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pagada_at TIMESTAMPTZ,
    CONSTRAINT chk_ordenes_estado CHECK (estado IN ('ABIERTA', 'PAGADA', 'EXPIRADA', 'CANCELADA')),
    CONSTRAINT chk_ordenes_importes CHECK (subtotal >= 0 AND descuento_total >= 0 AND importe_total >= 0)
);

CREATE TABLE orden_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes_compra(id) ON DELETE CASCADE,
    tipo_item VARCHAR(10) NOT NULL,
    referencia_id BIGINT NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    cantidad SMALLINT NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    importe_total NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_orden_items_tipo CHECK (tipo_item IN ('EVENTO', 'SESION')),
    CONSTRAINT chk_orden_items_importes CHECK (cantidad > 0 AND precio_unitario >= 0 AND importe_total >= 0)
);

CREATE TABLE metodos_pago_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES perfil_clientes(id) ON DELETE CASCADE,
    proveedor VARCHAR(50) NOT NULL,
    token_encriptado TEXT NOT NULL,
    marca VARCHAR(40),
    last4 VARCHAR(4),
    exp_month SMALLINT,
    exp_year SMALLINT,
    predeterminado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_metodos_pago_last4 CHECK (last4 IS NULL OR last4 ~ '^[0-9]{4}$'),
    CONSTRAINT chk_metodos_pago_exp_month CHECK (exp_month IS NULL OR exp_month BETWEEN 1 AND 12)
);

CREATE TABLE pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes_compra(id) ON DELETE RESTRICT,
    metodo_pago_cliente_id BIGINT REFERENCES metodos_pago_cliente(id) ON DELETE SET NULL,
    proveedor VARCHAR(50) NOT NULL,
    referencia_externa VARCHAR(150) UNIQUE,
    importe NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    mensaje_error TEXT,
    procesado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_pagos_estado CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'FALLIDO', 'REEMBOLSADO')),
    CONSTRAINT chk_pagos_importe CHECK (importe >= 0)
);

CREATE TABLE reembolsos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL REFERENCES pagos(id) ON DELETE RESTRICT,
    importe NUMERIC(10, 2) NOT NULL,
    motivo VARCHAR(255),
    referencia_externa VARCHAR(150),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reembolsos_estado CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    CONSTRAINT chk_reembolsos_importe CHECK (importe >= 0)
);

CREATE TABLE recibos_digitales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL UNIQUE REFERENCES pagos(id) ON DELETE RESTRICT,
    numero VARCHAR(40) NOT NULL UNIQUE,
    cliente_nombre VARCHAR(180) NOT NULL,
    cliente_email VARCHAR(150) NOT NULL,
    descripcion_compra TEXT NOT NULL,
    importe NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'VALIDO',
    emitido_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    anulado_at TIMESTAMPTZ,
    CONSTRAINT chk_recibos_estado CHECK (estado IN ('VALIDO', 'ANULADO')),
    CONSTRAINT chk_recibos_importe CHECK (importe >= 0)
);

CREATE TABLE reservas_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    orden_item_id BIGINT REFERENCES orden_items(id) ON DELETE SET NULL,
    cliente_id BIGINT NOT NULL REFERENCES perfil_clientes(id) ON DELETE RESTRICT,
    ocurrencia_id BIGINT NOT NULL REFERENCES ocurrencias_evento(id) ON DELETE RESTRICT,
    cantidad SMALLINT NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    importe_total NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    expira_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelada_at TIMESTAMPTZ,
    CONSTRAINT chk_reservas_evento_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'LISTA_ESPERA', 'COMPLETADA', 'NO_ASISTIO')),
    CONSTRAINT chk_reservas_evento_importes CHECK (cantidad > 0 AND precio_unitario >= 0 AND importe_total >= 0)
);

CREATE TABLE asistentes_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_evento_id BIGINT NOT NULL REFERENCES reservas_evento(id) ON DELETE CASCADE,
    nombre_asistente VARCHAR(150),
    email_asistente VARCHAR(150),
    telefono_asistente VARCHAR(25),
    estado_asistencia VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    registrado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    registrado_at TIMESTAMPTZ,
    CONSTRAINT chk_asistentes_estado CHECK (estado_asistencia IN ('PENDIENTE', 'ASISTIO', 'NO_ASISTIO'))
);

CREATE TABLE reservas_sesion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    orden_item_id BIGINT REFERENCES orden_items(id) ON DELETE SET NULL,
    cliente_id BIGINT NOT NULL REFERENCES perfil_clientes(id) ON DELETE RESTRICT,
    servicio_id BIGINT NOT NULL REFERENCES servicios_1a1(id) ON DELETE RESTRICT,
    profesional_id BIGINT NOT NULL REFERENCES perfil_profesionales(id) ON DELETE RESTRICT,
    inicio_at TIMESTAMPTZ NOT NULL,
    fin_at TIMESTAMPTZ NOT NULL,
    modalidad VARCHAR(15) NOT NULL,
    ubicacion_id BIGINT REFERENCES ubicaciones(id) ON DELETE SET NULL,
    url_virtual TEXT,
    precio NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    expira_at TIMESTAMPTZ,
    notas_cliente TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelada_at TIMESTAMPTZ,
    CONSTRAINT chk_reservas_sesion_modalidad CHECK (modalidad IN ('PRESENCIAL', 'ONLINE', 'AMBAS')),
    CONSTRAINT chk_reservas_sesion_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'LISTA_ESPERA', 'COMPLETADA', 'NO_ASISTIO')),
    CONSTRAINT chk_reservas_sesion_fechas CHECK (fin_at > inicio_at),
    CONSTRAINT chk_reservas_sesion_precio CHECK (precio >= 0)
);

CREATE TABLE historial_estados_reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reserva VARCHAR(10) NOT NULL,
    reserva_id BIGINT NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20) NOT NULL,
    cambiado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    motivo VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_historial_tipo_reserva CHECK (tipo_reserva IN ('EVENTO', 'SESION'))
);

CREATE TABLE favoritos (
    cliente_id BIGINT NOT NULL REFERENCES perfil_clientes(id) ON DELETE CASCADE,
    tipo_entidad VARCHAR(15) NOT NULL,
    entidad_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cliente_id, tipo_entidad, entidad_id),
    CONSTRAINT chk_favoritos_tipo CHECK (tipo_entidad IN ('EVENTO', 'SERVICIO', 'PROFESIONAL'))
);

CREATE TABLE secciones_inicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(80) NOT NULL UNIQUE,
    titulo VARCHAR(180),
    subtitulo TEXT,
    imagen_url TEXT,
    boton_texto VARCHAR(80),
    boton_url TEXT,
    orden SMALLINT NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    accion VARCHAR(40) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    entidad_id BIGINT,
    datos_anteriores TEXT,
    datos_nuevos TEXT,
    ip VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_usuarios_estado ON usuarios(estado);
CREATE INDEX idx_usuario_roles_rol_id ON usuario_roles(rol_id);
CREATE INDEX idx_refresh_tokens_usuario_id ON refresh_tokens(usuario_id);
CREATE INDEX idx_ubicaciones_activo ON ubicaciones(activo);
CREATE INDEX idx_categorias_evento_activo ON categorias_evento(activo);
CREATE INDEX idx_perfil_clientes_usuario_id ON perfil_clientes(usuario_id);
CREATE INDEX idx_perfil_prof_publicacion ON perfil_profesionales(estado_publicacion);
CREATE INDEX idx_eventos_estado ON eventos(estado);
CREATE INDEX idx_eventos_creado_por ON eventos(creado_por);
CREATE INDEX idx_ocurrencias_evento_evento_id ON ocurrencias_evento(evento_id);
CREATE INDEX idx_ocurrencias_evento_inicio_at ON ocurrencias_evento(inicio_at);
CREATE INDEX idx_servicios_profesional_id ON servicios_1a1(profesional_id);
CREATE INDEX idx_disponibilidad_profesional_id ON disponibilidad_profesional(profesional_id);
CREATE INDEX idx_ordenes_cliente_id ON ordenes_compra(cliente_id);
CREATE INDEX idx_pagos_orden_id ON pagos(orden_id);
CREATE INDEX idx_reservas_evento_ocurrencia_id ON reservas_evento(ocurrencia_id);
CREATE INDEX idx_reservas_evento_cliente_id ON reservas_evento(cliente_id);
CREATE INDEX idx_reservas_sesion_cliente_id ON reservas_sesion(cliente_id);
CREATE INDEX idx_historial_reserva ON historial_estados_reserva(tipo_reserva, reserva_id);
CREATE INDEX idx_auditoria_entidad ON auditoria(entidad, entidad_id);
