CREATE TABLE techniques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE work_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professional_techniques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_id BIGINT NOT NULL REFERENCES specialist_profiles(id) ON DELETE CASCADE,
    technique_id BIGINT NOT NULL REFERENCES techniques(id) ON DELETE RESTRICT,
    CONSTRAINT uk_professional_technique UNIQUE (specialist_id, technique_id)
);

CREATE TABLE professional_work_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_id BIGINT NOT NULL REFERENCES specialist_profiles(id) ON DELETE CASCADE,
    work_topic_id BIGINT NOT NULL REFERENCES work_topics(id) ON DELETE RESTRICT,
    CONSTRAINT uk_professional_work_topic UNIQUE (specialist_id, work_topic_id)
);

CREATE INDEX idx_professional_techniques_specialist_id
    ON professional_techniques(specialist_id);
CREATE INDEX idx_professional_work_topics_specialist_id
    ON professional_work_topics(specialist_id);
