CREATE TABLE meeting_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    platform VARCHAR(50) NOT NULL,
    meeting_url TEXT NOT NULL,
    meeting_id VARCHAR(100),
    password VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

ALTER TABLE event_occurrences ADD COLUMN meeting_link_id BIGINT REFERENCES meeting_links(id) ON DELETE SET NULL;
